name: Feature Request
description: Request a feature for Lenstube
labels: [needs review]
body:
  - type: textarea
    attributes:
      label: Description
      description: A concise description of the feature request.
      placeholder: Clearly describe what you want to see in Lenstube.
    validations:
      required: true
