name = "curated"
main = "src/index.ts"
compatibility_date = "2023-01-25"
routes = [
	{ pattern = "curated.lenstube.xyz", custom_domain = true }
]
keep_vars = true
kv_namespaces = [
  { binding = "CURATED", id = "516974865e4645e9b463aa8967253565", preview_id = "45045b1be62f4ad499b823ff91992ae1"  }
]

[triggers]
crons = ["0 0 * * *"]

[env.production.vars]
AIRTABLE_PAT = ""
