name = "curated"
main = "src/index.ts"
compatibility_date = "2023-01-25"
routes = [
	{ pattern = "curated.lenstube.xyz", custom_domain = true }
]
keep_vars = true

[triggers]
crons = ["0 0 * * *"]

kv_namespaces = [
  { binding = "CURATED_CHANNELS", id = "516974865e4645e9b463aa8967253565" }
]

[env.production.vars]
AIRTABLE_PAT = ""
