name = "api"
account_id="8c096dfa36dc8fff1771c356915965a3"
compatibility_date = "2023-01-01"
routes = [
	{ pattern = "api.dragverse.app", custom_domain = true }
]
keep_vars = true
node_compat = true

[env.production.vars]
EVER_ACCESS_KEY=""
EVER_ACCESS_SECRET=""
LOGTAIL_API_KEY=""
INGEST_REST_ENDPOINT=""
IP_API_KEY=""
WALLET_PRIVATE_KEY=""
LIVEPEER_API_TOKEN=""

[[d1_databases]]
binding = "TAPE_DB"
database_name = "tape-prod-d1"
database_id = "e50137a9-6c57-4ebd-96c3-78657d165fe4"
migrations_dir = "migrations"
