name: Export and Deploy

on:
  # workflow_run:
  #   branches: [main]
  #   workflows: [CI]
  #   types:
  #     - completed
  workflow_dispatch:
  
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
        - name: Check out repo ✅
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: Setup Node.js environment 📐
          uses: actions/setup-node@v3
          with:
            node-version-file: '.nvmrc'
            cache: 'yarn'
 
        - name: Install dependencies 🧳
          run: yarn install --frozen-lockfile
              
        - name: Build and Export 📦
          run: npx turbo run export

        - name: Publish to Cloudflare Pages 🚀
          uses: cloudflare/pages-action@1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: lenstube-web
            directory: apps/web/out
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
