name: Crowdin Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
          source: '/**/locales/en/*.po'
          translation: '/**/locales/%two_letters_code%/%original_file_name%'
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: i18n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'chore(i18n): sync translations'
          pull_request_body: 'New Crowdin translations by Crowdin GH Action'
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

